#:schema https://github.com/liblaf/llm-cli/raw/refs/heads/main/docs/schema/models.json
model = "deepseek-chat"
provider = "deepseek"

[providers.deepseek]
api_key = "sk-***"
base_url = "https://api.deepseek.com"
