# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: cf91a9d
_src_path: gh:liblaf/copier-python
author: liblaf
email: 30631553+liblaf@users.noreply.github.com
license: MIT
name: liblaf-ai-cli
owner: liblaf
repo: ai-cli
